### ISSUE TITLE
Pulsing effect of marker for MapBox maps

### ISSUE THREAD

**Issue by jimsavin** [sindresorhus/amas#124]
Hi Justin!

I’m currently working on Android project and trying implement pulsing effect for markers, like this:
https://github.com/TransitApp/SVPulsingAnnotationView https://github.com/TransitApp/SVPulsingAnnotationView

But I faced with issue that MapBox doesn’t have support for markers animation.
And our team decided ask your help - maybe you have idea how it may be implemented on Android?

**Comment by sindresorhus** [comment]
Wrong repo ;)
