### ISSUE TITLE
Tag answered issues instead of closing?

### ISSUE THREAD

**Issue by dcs619** [sindresorhus/amas#159]
I've noticed as I browse AMAs, the `closed` section is always more interesting than the `open` section, and I need to click through both views to see them.

I realize the default "open" view makes it easier for authors to find/answer new questions, but I'd suggest authors tag questions with an `Answered` flag instead of closing.  Thoughts?

**Comment by sindresorhus** [comment]
There's a link in the readme to go directly to answered questions.
