### ISSUE TITLE
About the 7-1 Pattern today

### ISSUE THREAD

**Issue by nuxion** [sindresorhus/amas#217]
Hi! I really liked your article about styling react components with a SASS approach [styling-react-components-in-sass](https://hugogiraudel.com/2015/06/18/styling-react-components-in-sass/). 

I wonder if today you choose the same pattern, or instead what alternative would you recommend?

Thanks,
Best regards,
Xavier

**Comment by sindresorhus** [comment]
I think you're asking this in the wrong AMA.
