### ISSUE TITLE
Are emojis allowed under the ama list?

### ISSUE THREAD

**Issue by simkimsia** [sindresorhus/amas#222]
I submitted a PR for my AMA at https://github.com/sindresorhus/amas/pull/221. Was wondering if emojis allowed. I wanted to add a flag emoji for my location and a chart emoji explaining my work in converting Excel to business apps. 

I didn't add any emoji in the end but wanted to clarify.

**Comment by sindresorhus** [comment]
No, it gets too noisy. You can have as many emoji as you want in your AMA's readme.
